/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senac.lanchonete;
import javax.swing.ImageIcon;
import java.awt.Image;
/**
 *
 * @author MIGUELVARGASFERREIRA
 */
public class TelaLanchonete extends javax.swing.JFrame {

    /**
     * Creates new form TelaLanchonete
     */
    public TelaLanchonete() {
        initComponents();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("shinji-removebg-preview.png"));
    Image img = icon.getImage();
    Image novaImg = img.getScaledInstance(150, 150, java.awt.Image.SCALE_SMOOTH);
    lblImage.setIcon(new ImageIcon(novaImg));
    lblImage.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        chkMonstro = new javax.swing.JCheckBox();
        lblCardapio = new javax.swing.JLabel();
        chkDogao = new javax.swing.JCheckBox();
        chkArepa1 = new javax.swing.JCheckBox();
        chkPastel = new javax.swing.JCheckBox();
        chkCoca = new javax.swing.JCheckBox();
        lblSubtitulos = new javax.swing.JLabel();
        chkAgua = new javax.swing.JCheckBox();
        chkSuco = new javax.swing.JCheckBox();
        lblSubtitulos3 = new javax.swing.JLabel();
        chkTrufa = new javax.swing.JCheckBox();
        lblSubtitulos1 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(245, 130, 32));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Lanchonete do Senac");
        lblTitulo.setFocusable(false);

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 213, 79))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 213, 79));
        jPanel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        chkMonstro.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        chkMonstro.setText("XIS Monstro - 31,00 R$");
        chkMonstro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMonstroActionPerformed(evt);
            }
        });

        lblCardapio.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCardapio.setForeground(new java.awt.Color(0, 51, 102));
        lblCardapio.setText("Cardápio");

        chkDogao.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        chkDogao.setText("Dogão - 12,00 R$");
        chkDogao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDogaoActionPerformed(evt);
            }
        });

        chkArepa1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        chkArepa1.setText("Arepa - 15,00 R$");
        chkArepa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkArepa1ActionPerformed(evt);
            }
        });

        chkPastel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        chkPastel.setText("Pastel - 10,00 R$");
        chkPastel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPastelActionPerformed(evt);
            }
        });

        chkCoca.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        chkCoca.setText("Coca - 7,00 R$");
        chkCoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCocaActionPerformed(evt);
            }
        });

        lblSubtitulos.setBackground(new java.awt.Color(0, 51, 102));
        lblSubtitulos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblSubtitulos.setForeground(new java.awt.Color(0, 51, 102));
        lblSubtitulos.setText("Lanches");

        chkAgua.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        chkAgua.setText("Água - 4,00 R$");
        chkAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAguaActionPerformed(evt);
            }
        });

        chkSuco.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        chkSuco.setText("Suco de Uva - 5,00 R$");
        chkSuco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSucoActionPerformed(evt);
            }
        });

        lblSubtitulos3.setBackground(new java.awt.Color(0, 51, 102));
        lblSubtitulos3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblSubtitulos3.setForeground(new java.awt.Color(0, 51, 102));
        lblSubtitulos3.setText("Doces");

        chkTrufa.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        chkTrufa.setText("Trufa - 8,00 R$");
        chkTrufa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkTrufa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTrufaActionPerformed(evt);
            }
        });

        lblSubtitulos1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblSubtitulos1.setForeground(new java.awt.Color(0, 51, 102));
        lblSubtitulos1.setText("Bebidas");

        lblTotal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblTotal.setText("00,00");

        lblImage.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setText("Total:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(lblSubtitulos))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkPastel)
                                    .addComponent(chkDogao)
                                    .addComponent(chkArepa1)
                                    .addComponent(chkMonstro)
                                    .addComponent(chkTrufa))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblSubtitulos1)
                                .addGap(67, 67, 67))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chkSuco)
                                .addComponent(chkAgua)
                                .addComponent(chkCoca))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblSubtitulos3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblImage)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCardapio)
                .addGap(134, 134, 134))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblSubtitulos)
                        .addGap(8, 8, 8)
                        .addComponent(chkMonstro)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(chkDogao))
                            .addComponent(chkArepa1))
                        .addGap(18, 18, 18)
                        .addComponent(chkPastel)
                        .addGap(20, 20, 20)
                        .addComponent(lblSubtitulos3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblCardapio)
                        .addGap(18, 18, 18)
                        .addComponent(lblSubtitulos1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkCoca)
                        .addGap(12, 12, 12)
                        .addComponent(chkAgua)
                        .addGap(13, 13, 13)
                        .addComponent(chkSuco)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkTrufa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTotal))
                .addGap(24, 24, 24)
                .addComponent(lblImage))
        );

        btnCalcular.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnCalcular.setText("Calcular Total");
        btnCalcular.setBorder(new javax.swing.border.MatteBorder(null));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.setBorder(new javax.swing.border.MatteBorder(null));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkTrufaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTrufaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkTrufaActionPerformed

    private void chkSucoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSucoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSucoActionPerformed

    private void chkAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAguaActionPerformed

    private void chkCocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCocaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCocaActionPerformed

    private void chkPastelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPastelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPastelActionPerformed

    private void chkArepa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkArepa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkArepa1ActionPerformed

    private void chkDogaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDogaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDogaoActionPerformed

    private void chkMonstroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMonstroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMonstroActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
    double total = 0;
        if (chkMonstro.isSelected()) total += 31;
        if (chkArepa1.isSelected()) total += 15;
        if (chkDogao.isSelected()) total += 12;
        if (chkPastel.isSelected()) total += 10;
        if (chkCoca.isSelected()) total += 7;
        if(chkTrufa.isSelected()) total += 8;
        if (chkAgua.isSelected()) total += 4;
        if (chkSuco.isSelected()) total += 5;
        
            
        lblTotal.setText(String.format("%.2f", total));
        
        if (total == 0 ) {
            lblTotal.setForeground(new java.awt.Color(200,0,0));
            lblTotal.setText("Nenhum item selecionado!");
        }else if (total < 0) {
            lblTotal.setForeground(new java.awt.Color(0,100,0));
        } else if (total <= 25) {
            lblTotal.setForeground(new java.awt.Color(0,128,255));
        } else{
             lblTotal.setForeground(new java.awt.Color(255,128,9));
             lblTotal.setText(String.format("Pedido completo! Total: %.2f", total));
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
              // TODO add your handling code here:
              chkAgua.setSelected(false);
              chkArepa1.setSelected(false);
              chkCoca.setSelected(false);
              chkDogao.setSelected(false);
              chkMonstro.setSelected(false);
              chkTrufa.setSelected(false);
              chkPastel.setSelected(false);
              chkSuco.setSelected(false);
              
              lblTotal.setText("00,00");
              lblTotal.setForeground(new java.awt.Color(0,0,0));
              
            
        }
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLanchonete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLanchonete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLanchonete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLanchonete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLanchonete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JCheckBox chkAgua;
    private javax.swing.JCheckBox chkArepa1;
    private javax.swing.JCheckBox chkCoca;
    private javax.swing.JCheckBox chkDogao;
    private javax.swing.JCheckBox chkMonstro;
    private javax.swing.JCheckBox chkPastel;
    private javax.swing.JCheckBox chkSuco;
    private javax.swing.JCheckBox chkTrufa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblCardapio;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblSubtitulos;
    private javax.swing.JLabel lblSubtitulos1;
    private javax.swing.JLabel lblSubtitulos3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
