/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senac.JogoDeClicks;
import java.awt.Graphics;
import java.awt.event.ActionEvent; // para escutar os eventos de click!
import java.awt.event.ActionListener;
import java.util.Random; // para randomizar os aparecimentos do btn.
import javax.swing.Timer; // extenção mais atualizada !
/**
 *
 * @author MIGUELVARGASFERREIRA
 */
public class telaJogo extends javax.swing.JFrame {
// variavel  do jogo;
    int pontos = 0;
    int tempo = 30;
    Timer timerMovimento; // controla o quadrado
    Timer timerTempo; // cronometro
    
    Random randow = new Random();
    
    /**
     * Creates new form telaJogo
     */
    public telaJogo() {
        initComponents();
        setLocationRelativeTo(null); // centraliza
        iniciarJogo();
        panelDoTitulo.setBorder(new RoundedBorder(20));
        panelDoJogo.setBorder(new RoundedBorder(20));
        
        
        
    }
    void iniciarJogo(){
        pontos = 0;
        tempo = 30;
        lblPontos.setText("Pontos: 0"); // atualiza o rotulo na tela;
        lblTempo.setText("Tempo:30"); // mesma coisa, atualiza o rotulo do tempo ao iniciar;
        
        
        timerMovimento = new Timer(600, e -> moverQuadrado());
        
        
        timerMovimento.start();
        
        timerTempo = new Timer(1000, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e ){
                tempo--;
                lblTempo.setText(("Tempo " + tempo));
                
                if (tempo <= 0 ) {
                    timerMovimento.stop(); // para o movimento;
                    timerTempo.stop(); // para o cronometro;
                    
                    // Mostra uma janelainfromando o fim do jogo //
                    javax.swing.JOptionPane.showInternalMessageDialog( null, "Tempo esgotado! \nPontos " + pontos, "Fim de jogo",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    
                }
            }
        });
        timerTempo.start(); // inicia o cronometro;
        // fim do metodo iniciar;
        
        
    }
    void moverQuadrado(){
        int maxX = panelDoJogo.getWidth() - btnQuadrado.getWidth();
        // a mesma coisa pra y (vertical: );
        int maxY = panelDoJogo.getHeight() - btnQuadrado.getHeight();
        
        if( maxX < 0 || maxY < 0) return;
            
        
        
        int y = randow.nextInt(Math.max(1, maxY));
        int x = randow.nextInt(Math.max(1, maxX));
        // move o quadrado para a nova posição dentro do painel
        btnQuadrado.setLocation(x,y);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnImagemDeFundo = new javax.swing.JPanel();
        panelDoJogo = new javax.swing.JPanel();
        btnQuadrado = new javax.swing.JButton();
        panelDoTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblTempo = new javax.swing.JLabel();
        lblPontos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDoJogo.setBackground(new java.awt.Color(204, 204, 255));

        btnQuadrado.setBackground(new java.awt.Color(204, 204, 255));
        btnQuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senac/JogoDeClicks/assets/img/pngegg (6) (1).png"))); // NOI18N
        btnQuadrado.setBorder(null);
        btnQuadrado.setBorderPainted(false);
        btnQuadrado.setContentAreaFilled(false);
        btnQuadrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuadrado.setDefaultCapable(false);
        btnQuadrado.setPreferredSize(new java.awt.Dimension(50, 50));
        btnQuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuadradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDoJogoLayout = new javax.swing.GroupLayout(panelDoJogo);
        panelDoJogo.setLayout(panelDoJogoLayout);
        panelDoJogoLayout.setHorizontalGroup(
            panelDoJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDoJogoLayout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addComponent(btnQuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(269, 269, 269))
        );
        panelDoJogoLayout.setVerticalGroup(
            panelDoJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDoJogoLayout.createSequentialGroup()
                .addContainerGap(278, Short.MAX_VALUE)
                .addComponent(btnQuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247))
        );

        panelDoTitulo.setBackground(new java.awt.Color(204, 204, 255));

        lblTitulo.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senac/JogoDeClicks/assets/img/Cookie_Clicker_Logo (1).png"))); // NOI18N

        javax.swing.GroupLayout panelDoTituloLayout = new javax.swing.GroupLayout(panelDoTitulo);
        panelDoTitulo.setLayout(panelDoTituloLayout);
        panelDoTituloLayout.setHorizontalGroup(
            panelDoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDoTituloLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lblTitulo)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        panelDoTituloLayout.setVerticalGroup(
            panelDoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDoTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        lblTempo.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        lblTempo.setText("Tempo: 30");

        lblPontos.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        lblPontos.setText("Pontos: 0");

        javax.swing.GroupLayout jpnImagemDeFundoLayout = new javax.swing.GroupLayout(jpnImagemDeFundo);
        jpnImagemDeFundo.setLayout(jpnImagemDeFundoLayout);
        jpnImagemDeFundoLayout.setHorizontalGroup(
            jpnImagemDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnImagemDeFundoLayout.createSequentialGroup()
                .addGroup(jpnImagemDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnImagemDeFundoLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jpnImagemDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpnImagemDeFundoLayout.createSequentialGroup()
                                .addComponent(lblTempo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPontos))
                            .addComponent(panelDoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnImagemDeFundoLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(panelDoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jpnImagemDeFundoLayout.setVerticalGroup(
            jpnImagemDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnImagemDeFundoLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(panelDoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnImagemDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPontos)
                    .addComponent(lblTempo))
                .addGap(9, 9, 9)
                .addComponent(panelDoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnImagemDeFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnImagemDeFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuadradoActionPerformed
      
         
    lblPontos.setText("Pontos: " + pontos); // atualiza o texto na tela
        pontos++;
        
    }//GEN-LAST:event_btnQuadradoActionPerformed

    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuadrado;
    private javax.swing.JPanel jpnImagemDeFundo;
    private javax.swing.JLabel lblPontos;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelDoJogo;
    private javax.swing.JPanel panelDoTitulo;
    // End of variables declaration//GEN-END:variables
}